name: ai_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  bloc: ^9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  sign_in_with_apple: ^8.1.0
  supabase_flutter: ^2.14.2

dev_dependencies:
  bloc_lint: ^0.4.1
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
